version: '3.8'

services:
    django:
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
            - redis
            - celery-management
            - celery-listener
            - celery-poster
        networks:
            - private_network

    db:
        image: postgres:17-alpine
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - private_network

    redis:
        image: redis:alpine
        command: redis-server --save "" --appendonly no
        volumes:
            - redis-data:/data
        networks:
            - private_network

    celery-management:
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        command: celery -A core worker --loglevel=info -Q management -n management@%h
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - db
            - redis
        networks:
            - private_network

    celery-listener:
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        command: celery -A core worker --loglevel=info -Q listener -n listener@%h --pool=prefork --concurrency=4
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - db
            - redis
        networks:
            - private_network

    celery-poster:
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        command: celery -A core worker --loglevel=info -Q poster -n poster@%h
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - db
            - redis
        networks:
            - private_network

    celery-beat:
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        command: celery -A core beat --loglevel=info
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - db
            - redis
        networks:
            - private_network

volumes:
    postgres_data:
    redis-data:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs

networks:
    private_network:
        driver: bridge
