services:
    django:
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
            - redis
            - celery
            - celery-beat

    db:
        image: postgres:17-alpine
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    celery:
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        command: celery -A core worker --loglevel=info
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - db
            - redis

    celery-beat:
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        command: celery -A core beat --loglevel=info
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - db
            - redis

volumes:
    postgres_data:
