services:
    django:
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
            - redis
            - celery-management
            - celery-listener
            - celery-poster

    db:
        image: postgres:17-alpine
        env_file:
            - .env
        ports:
            -   "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    celery-management:
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        command: celery -A core worker --loglevel=info -Q management -n management@%h
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - db
            - redis

    celery-listener:
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        command: celery -A core worker --loglevel=info -Q listener -n listener@%h
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - db
            - redis

    celery-poster:
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        command: celery -A core worker --loglevel=info -Q poster -n poster@%h
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - db
            - redis

    celery-beat:
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        command: celery -A core beat --loglevel=info
        volumes:
            - .:/code
        env_file:
            - .env
        depends_on:
            - db
            - redis

volumes:
    postgres_data:
