# Generated by Django 5.1.2 on 2024-11-23 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from ..validators import validate_url


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('source_link', models.URLField(max_length=128, unique=True, validators=[validate_url])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_post', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SourceChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('source_link', models.URLField(max_length=128, unique=True, validators=[validate_url])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_following', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL)),
                ('target_channel', models.ManyToManyField(related_name='source_channels', to='tracker.targetchannel')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tracker.sourcechannel')),
            ],
        ),
    ]
