# Generated by Django 5.1.2 on 2024-12-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_targetchannel_user_alter_sourcechannel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcechannel',
            name='verified_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='targetchannel',
            name='verified_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sourcechannel',
            name='active_following',
            field=models.BooleanField(default=False),
        ),
    ]
