# Generated by Django 5.1.2 on 2024-12-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_sourcechannel_verified_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetchannel',
            name='admin_status',
            field=models.BooleanField(default=False),
        ),
    ]
