name: Docker Compose Tests Check

on:
  pull_request:
    branches:
      - main

jobs:
  deployment-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
            echo "POSTGRES_NAME=postgres" >> .env
            echo "POSTGRES_USER=postgres" >> .env
            echo "POSTGRES_PASSWORD=postgres" >> .env
            echo "POSTGRES_HOST=db" >> .env
            echo "POSTGRES_PORT=5432" >> .env
            echo "SECRET_KEY=develop" >> .env

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Start services with Docker Compose
        run: docker-compose up -d --build

      - name: Run Tests
        run: |
          docker-compose exec -T django pytest
