name: Docker Compose Deployment Check

on:
  pull_request:
    branches:
      - main

jobs:
  deployment-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
            echo "POSTGRES_NAME=${{ vars.POSTGRES_NAME }}" >> .env
            echo "POSTGRES_USER=${{ vars.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ vars.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_HOST=${{ vars.POSTGRES_HOST }}" >> .env
            echo "POSTGRES_PORT=${{ vars.POSTGRES_PORT }}" >> .env
            echo "SECRET_KEY=${{ vars.SECRET_KEY }}" >> .env

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Start services with Docker Compose
        run: docker-compose up -d --build

      - name: Wait for Django to be healthy
        run: |
          for i in {1..10}; do
            if docker-compose ps | grep "django.*healthy"; then
              echo "Django container is starts correctly!"
              exit 0
            else
              echo "Waiting for Django container to be healthy..."
              sleep 5
            fi
          done
          echo "Django container did not become healthy in time" && exit 1

      - name: Run migrations
        run: |
          docker-compose exec django python manage.py migrate || { echo 'Migrations failed'; exit 1; }
