name: Docker Compose Deployment Check

on:
  pull_request:
    branches:
      - main

jobs:
  deployment-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
            echo "POSTGRES_NAME=postgres" >> .env
            echo "POSTGRES_USER=postgres" >> .env
            echo "POSTGRES_PASSWORD=postgres" >> .env
            echo "POSTGRES_HOST=db" >> .env
            echo "POSTGRES_PORT=5432" >> .env
            echo "SECRET_KEY=develop" >> .env
            echo "REDIS_URL=redis://redis:6379/0" >> .env
            echo "BOT_TOKEN=develop" >> .env
            echo "API_ID=123" >> .env
            echo "API_HASH=321" >> .env
            echo "TELEGRAM_SESSION=${{ secrets.TELEGRAM_BOT_SESSION }}" >> .env
            echo "API_BOT_ID=234" >> .env
            echo "API_BOT_HASH=234" >> .env
            echo "BOT_TELEGRAM_SESSION=${{ secrets.TELEGRAM_BOT_SESSION }}" >> .env



      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Start services with Docker Compose
        run: docker-compose up -f docker-compose-dev.yml -d --build

      - name: Run migrations
        run: |
          docker-compose exec -f docker-compose-dev.yml -T django python manage.py migrate || { echo 'Migrations failed'; exit 1; }
